tables_config:
  TABLE_NAME_A:
    - path: SOURCE_A.xlsx
      sheet: A.1
      datetime:
        FIELD_1:
        FIELD_2: "%Y-%m"
      pivot:
        index: FIELD_ID
        columns: FIELD_KEY
        values: FIELD_VALUE
      include_index: false
  TABLE_NAME_B:
    - path: SOURCE_B.csv
