tables_config:
  TABLE_NAME_A:
    - path: SOURCE_A.xlsx
      sheet: A.1
      datetime:
        COLUMN_1:
        COLUMN_2: "%Y-%m"
      pivot:
        index: ID_COLUMN
        columns: KEY_COLUMN
        values: VALUE_COLUMN
      include_index: false
  TABLE_NAME_B:
    - path: SOURCE_B1.csv
    - path: SOURCE_B2.csv
