---
# Config options.
# See define_config_options()
include:
  - path: "PATH"
tables_config:
  TABLE_NAME_01:
    - path: "PATH_01"
    - path: "PATH_02"
      sheet: "SHEET NAME"
      datetime:
        FIELD_01: NONE_OR_STR
        FIELD_02: NONE_OR_STR
      pivot:
        index: FIELD_ID
        columns: FIELD_KEY
        values: FIELD_VALUE
create_tables:
  # If no create_tables is provided, all tables in tables_config are created.
  - TABLE_NAME_01
  - INCLUDED_TABLE_02
output:
  dir: "PATH"
  basename: "BASENAME"
  export_queries: csv
  export_tables: csv
  append_date: true
  prepend_date: true
  styles:
    column_width: 15
import_module:
  - module: "MODULE_NAME"
import:
  strip: true
  slugify_columns: true
  lowercase_columns: true
  uppercase_rows: true
queries:
  - sheet: "SHEET NAME"
    sql: >-
      YOUR SQL
      ;
    datetime: true
    df_postprocess: FUNCTION_NAME
    replace:
      COLUMN_NAME:
        FIELD_MATCH: FIELD_REPLACE
