# Stub YAML to begin your report.
# See examples/ for more options.

# If you want to add a df_postprocess function, see report.py
import:
  - path: MODULE_A.py

include:
  - path: INCLUDE_A.yaml
  - path: INCLUDE_B.yaml

output:
  dir: output
  basename: BASENAME
  prepend_date: true
  export_tables: csv
  export_queries: csv
  styles:
    column_width: 15

input:
  strip: true
  slugify_columns: true
  lowercase_columns: true

tables_config:
  table_from_spreadsheet:
    - path: SOURCE_A.xlsx
      sheet: SHEET A.1
  table_from_csv:
    - path: SOURCE_B.csv
  table_from_multiple_sources:
    - path: SOURCE_C.xlsx
      sheet: SHEET C.1
    - path: SOURCE_C.xlsx
      sheet: SHEET C.2
      datetime:
        created:
        last_saved: "%Y-%m-%d"
      pivot:
        index: FIELD_ID
        columns: FIELD_KEY
        values: FIELD_VALUE
    - path: SOURCE_A.xlsx
      sheet: SHEET A.2
    - path: SOURCE_D.csv

# Because we have create_tables, we must manually specify each table we want,
# including the tables defined in tables_config. In this example, we
# do not create table_from_multiple_sources.
create_tables:
  - table_from_spreadsheet
  - table_from_csv
  - table_from_includes1
  - table_from_includes2
  - table_from_includes3

queries:
  - name: QUERY A
    sql: |
      SELECT
      *
      FROM
      table_from_spreadsheet AS s
      ;

  - name: QUERY B
    df_postprocess: postprocess_df
    sql: |
      SELECT
      *
      FROM
      table_from_spreadsheet AS s
      JOIN
      table_from_csv AS c
      ON
      s.id = c.id
      ;
